use_default_settings: true

general:
  instance_name: "SearXNG Local"

search:
  safe_search: 0
  autocomplete: ""
  default_lang: "all"
  formats:
    - html
    - json

outgoing:
  proxies:
    all://:
      - socks5h://host.docker.internal:7890
  using_tor_proxy: false

server:
  secret_key: "53d058421bd63f2be025b3e73731d275e1bf2a1bc98bd74ff0bff92c9e94e680"
  limiter: false
  image_proxy: true

ui:
  static_use_hash: true

engines:
  - name: google
    engine: google
    shortcut: g
    disabled: false
  - name: bing
    engine: bing
    shortcut: b
    disabled: false
  - name: duckduckgo
    engine: duckduckgo
    shortcut: ddg
    disabled: false
  - name: wikipedia
    engine: wikipedia
    shortcut: wp
    disabled: false
  - name: github
    engine: github
    shortcut: gh
    disabled: false
