#!/usr/bin/env python3
"""build-feedback-loop.py — Phase 0.6 bug 诊断辅助（v7.1 新增）。

辅助构造 minimal reproduction loop。给定 bug 描述 + 项目信息，
生成 reproduction 模板（test / script / curl 三选一）。

Usage:
    build-feedback-loop.py --bug "login 偶发 500 错误" \\
        --type test|script|curl \\
        --file src/auth/login.py \\
        --out repro_template.py
"""
from __future__ import annotations

import argparse
import sys
from pathlib import Path

TEMPLATES = {
    'test': '''#!/usr/bin/env python3
"""Minimal reproduction for: {bug}

Generated by build-feedback-loop.py (Phase 0.6).
Goal: 最小复现 → 步骤 1（feedback loop）。
"""
import pytest
from {module_path} import {target_symbol}


def test_reproduce_{slug}():
    """最小复现：每次都能触发 bug。"""
    # Arrange - 最小 fixture
    {arrange}

    # Act - 触发 bug 的最小调用
    result = {act}

    # Assert - bug 应该让这个 assertion 失败
    # RED 状态：bug 存在时这个 test 应失败
    assert result == {expected}, f"bug 复现: {{result}} != {{'{expected}'}}"


if __name__ == "__main__":
    # 直接跑：python repro_template.py
    test_reproduce_{slug}()
    print("❌ bug 未复现 - loop 失败，需 sharpen")
''',

    'script': '''#!/usr/bin/env bash
# Minimal reproduction for: {bug}
# Generated by build-feedback-loop.py (Phase 0.6).
# Goal: 最小复现 → 步骤 1（feedback loop）。

set -euo pipefail

# Arrange - 最小环境
export {env_vars}

# Act - 触发 bug 的最小调用
echo "→ 触发 bug: {act}"
OUTPUT=$({act}) || echo "→ exit code: $?"

# Assert - bug 应该让这里失败
echo "→ 实际输出: $OUTPUT"
echo "→ 期望输出: {expected}"
echo ""
echo "如果输出不一致 = bug 复现成功 → 进步骤 2（hypothesise）"
echo "如果输出一致 = loop 失败 → sharpen loop（不是直接 hypothesise）"
''',

    'curl': '''#!/usr/bin/env bash
# Minimal reproduction for: {bug}
# Generated by build-feedback-loop.py (Phase 0.6).
# Goal: 最小复现 → 步骤 1（feedback loop）。

set -euo pipefail

# Arrange - 最小 HTTP 请求
URL="{url}"
HEADERS=(-H "Content-Type: application/json")
BODY='{body}'

# Act - 触发 bug 的最小请求
echo "→ POST $URL"
RESPONSE=$(curl -sS -X POST "$URL" \\
    "''${HEADERS[@]}" \\
    -d "$BODY" \\
    -w "\\nHTTP_STATUS:%{{http_code}}")

HTTP_CODE=$(echo "$RESPONSE" | grep -oP 'HTTP_STATUS:\\K\\d+')
BODY_RESP=$(echo "$RESPONSE" | sed 's/HTTP_STATUS:\\d*$//')

echo "→ HTTP status: $HTTP_CODE"
echo "→ Body: $BODY_RESP"

# Assert
EXPECTED_STATUS="{expected_status}"
if [[ "$HTTP_CODE" != "$EXPECTED_STATUS" ]]; then
    echo "✅ bug 复现: HTTP $HTTP_CODE != $EXPECTED_STATUS"
    echo "→ 进步骤 2（hypothesise）"
else
    echo "❌ bug 未复现 → sharpen loop"
fi
''',
}


def slugify(s: str) -> str:
    import re
    s = re.sub(r'[^a-zA-Z0-9_]+', '_', s.lower()).strip('_')
    return s[:30] or 'bug'


def main() -> int:
    parser = argparse.ArgumentParser(description='Phase 0.6 reproduction loop 构造器')
    parser.add_argument('--bug', required=True, help='bug 描述')
    parser.add_argument('--type', choices=['test', 'script', 'curl'],
                        default='test', help='reproduction 类型')
    parser.add_argument('--file', help='相关文件（test 类型用）')
    parser.add_argument('--out', default='repro_template',
                        help='输出文件（自动加扩展名）')
    parser.add_argument('--url', default='http://localhost:8000/api',
                        help='curl 类型的 URL')
    parser.add_argument('--body', default='{}', help='curl body')
    parser.add_argument('--expected', default='EXPECTED',
                        help='期望值（test/script）')
    parser.add_argument('--expected-status', default='200',
                        help='期望 HTTP 状态（curl）')
    args = parser.parse_args()

    slug = slugify(args.bug)

    ctx = {
        'bug': args.bug,
        'slug': slug,
        'module_path': 'src.' + Path(args.file or 'x').stem.replace('/', '.') if args.file else 'module',
        'target_symbol': 'TARGET_FUNC',
        'arrange': '# 最小 fixture（手动填）',
        'act': '# 触发调用（手动填）',
        'expected': args.expected,
        'env_vars': 'ENV_VAR=value',
        'url': args.url,
        'body': args.body,
        'expected_status': args.expected_status,
    }

    template = TEMPLATES[args.type]
    content = template.format(**ctx)

    ext = '.py' if args.type == 'test' else '.sh'
    out = Path(args.out + ext)
    out.write_text(content, encoding='utf-8')
    if ext == '.sh':
        out.chmod(0o755)

    print(f'✅ {args.type} loop template generated: {out}')
    print(f'   下一步：手动填 Arrange/Act，跑 test，')
    print(f'   - 失败 = bug 复现 → 进步骤 2 hypothesise')
    print(f'   - 通过 = loop 失败 → sharpen loop（不是 hypothesise）')
    return 0


if __name__ == '__main__':
    sys.exit(main())
